### ISSUE TITLE
Too many new lines

### ISSUE THREAD

**Issue by eMarek** [release-it/keep-a-changelog#11]
Version `2.2.0` and `2.2.1` are somehow broken. When you make a new release this happens with your `CHANGELOG.md` file:

<img width="678" alt="Screenshot 2020-11-29 at 21 20 58" src="https://user-images.githubusercontent.com/311634/100552854-112d7700-328a-11eb-941d-ee20d327576b.png">

The "Unreleased" title is correctly updated with version number and date is added, but as you can see on screenshot there are 2 more new lines added in front of that.

My plugin config:
```
    "@release-it/keep-a-changelog": {
      "filename": "CHANGELOG.md",
      "strictLatest": false
    }
```

Version `2.1.0` works as it should.

**Comment by webpro** [comment]
Thanks @eMarek, fixed up some issues in the tests that revealed the error, which in turn should now also be fixed in [v2.2.2](https://github.com/release-it/keep-a-changelog/releases/tag/2.2.2).
