### ISSUE TITLE
Can't auto generate changelog

### ISSUE THREAD

**Issue by crimson-med** [release-it/keep-a-changelog#3]
Tried to use by itself and it would create the basic `CHANGELOG.md`

Tried to generate it with:

it said missing: `Missing "Unreleased" section in CHANGELOG.md.`

Tried to generate it with: https://www.npmjs.com/package/auto-changelog

it said missing: `Missing "Unreleased" section in CHANGELOG.md.`

I tried adding the section manually to my `CHANGELOG.md` and both got the error:
`There are no entries under "Unreleased" section in CHANGELOG.md.`

Project: https://github.com/crimson-med/vestigo

**Comment by eMarek** [comment]
Plugin first looks for `\n\n## [Unreleased]\n\n` inside `CHANGELOG.md` file and you get `Missing "Unreleased" section in CHANGELOG.md.` error message if this is not found.

Then it looks for the content between unreleased title and latest version title. More precise if your latest version is 1.0.0, then it looks for the content between `\n\n## [Unreleased]\n\n` and `\n\n## [1.0.0]`. You will get `There are no entries under "Unreleased" section in CHANGELOG.md.` error message if no content is found.

**Comment by eMarek** [comment]
@webpro I am thinking if we should alter this plugin that would look for changelog content between `\n\n## [Unreleased]\n\n` and `\n\n##`. It would not look for latest version. What do you think?

**Comment by eMarek** [comment]
Opened pull request: https://github.com/release-it/keep-a-changelog/pull/4

**Comment by webpro** [comment]
Sorry for the delay! Agreed on all points. Closing this by [v1.1.0](https://github.com/release-it/keep-a-changelog/releases/tag/1.1.0)
