### ISSUE TITLE
Write what this plugin does

### ISSUE THREAD

**Issue by gander** [release-it/keep-a-changelog#30]
Not everyone has time to solve puzzles as to why this plugin is not working. This plugin works. It does what it was designed to do, but there is no information as to what it actually does? If I immediately found out that this plugin replaces the `## [Unreleased]` header with the current version and release date, it would be clear that this is not what I expected from it. But there is no such information, so I wasted a lot of time to discover it. Sorry, just stating that you adhere to some standard is not exhaustive information about what this plugin does.

**Comment by gander** [comment]
Has anything changed since the last comment?

**Comment by webpro** [comment]
Yes, there have been some changes and releases since. Agreed the docs aren't very extensive. Anybody can feel free to open a pull request and improve it.
