### ISSUE TITLE
keep-a-changelog  does not mantain a changelog

### ISSUE THREAD

**Issue by cschroeter** [release-it/keep-a-changelog#33]
;)

**Comment by webpro** [comment]
Personally I just use https://github.com/release-it/keep-a-changelog/releases for this.

Not using other tools for this myself, just the default `git.changelog` release-it option.

**Comment by cschroeter** [comment]
No worries. It just funny since https://keepachangelog.com/en/1.1.0/ kinda expects you to maintain a `Changelog.md`

<img width="650" alt="image" src="https://github.com/release-it/keep-a-changelog/assets/1846056/b6db6675-131e-430d-af74-a82ddca8ba97">

**Comment by webpro** [comment]
Totally understand the irony here, just don't have the time to maintain e.g. release-it plugins that well :)
