### ISSUE TITLE
Fails if change log uses \r\n for new lines

### ISSUE THREAD

**Issue by mattheyan** [release-it/keep-a-changelog#5]
First off, I'm a Windows user...  😄 

I got the `Missing "Unreleased" section in CHANGELOG.md.` error even though my change log does have an "Unreleased" section. I changed newlines in my change log from `\r\n` to `\n`, and this got me past the error. But, since people are using the `autocrlf` setting, I don't think this would be a workable long-term solution.

Seems like the test could easily be changed to use regular expressions (i.e. `\r?\n`). What do you think?

**Comment by webpro** [comment]
Agreed, I'll try and fix it shortly

**Comment by webpro** [comment]
Released in [v1.1.1](https://github.com/release-it/keep-a-changelog/releases/tag/1.1.1)
