### ISSUE TITLE
Prototype pollution security issue

### ISSUE THREAD

**Issue by eMarek** [release-it/keep-a-changelog#6]
When I run `yarn install` on my project I get this warning:

`warning @release-it/keep-a-changelog > release-it > deprecated-obj > flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.`

I don't really understand why I get this warning only if `yarn.lock` is not generated yet and also `yarn audit` does not complain at all. Weird. Also no warnings on main `release-it` package. Super weird.

However, @webpro could you please upgrade https://github.com/webpro/deprecated-obj dependencies?

**Comment by webpro** [comment]
Thanks for this @eMarek. I've updated the dependencies of deprecated-obj (v2) and this will land in release-it soon (I'm working on v14)
