### ISSUE TITLE
Add version URLs

### ISSUE THREAD

**Issue by darekkay** [release-it/keep-a-changelog#8]
Thanks for providing this plugin. Apart from the open PR, there's just one thing I am currently missing. According to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), the URLs should be added on the bottom of the markdown document:

```
## [Unreleased]

## [1.0.0] - 2017-06-20
### Added
- New visual identity

...

[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v1.0.0...HEAD
[1.0.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.3.0...v1.0.0
```

This is not only useful to view the actual changeset, it also has a visual effect: if a URL is defined, the version will be rendered as "1.0.0" instead of "[1.0.0]". This approach is an alternative markdown syntax for links (see [example](https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md)).

If this is a change you'd like to see (behind a config option), I can give it a try.

**Comment by webpro** [comment]
Nice. Perhaps that should even be the default, but probably good to do that in a major bump later, when this works fine behind the option flag. Your PR is welcome!

**Comment by darekkay** [comment]
Hey @webpro , I've got a working implementation, but I had to inherit the plugin from `GitBase` instead of `Plugin`, so I have access to the Git repository (for automatic URL creation). However, now most unit tests are failing, because the test runner is accessing the the actual repository of the plugin - so the `latestVersion` is `2.1.0` (instead of the `1.0.0` in the mock data).

1. Is my approach of using `GitBase` okay? The only alternative I see would be to have the user pass the repository URL as a second config option.
2. If using `GitBase` is fine, how can I mock the Git usage in `release-it`?

Here's my WIP state: https://github.com/release-it/keep-a-changelog/commit/8960e78eb269610fb80184bd9731d9710bf03cba

It's quite some code, because I tried to handle all possible use cases (using `1.0.0` vs `v1.0.0`, using the option for the first time vs. when the version URLs are already available).

**Comment by webpro** [comment]
Thanks Darek,

Here some comments:

- Please extend from the Plugin class. The `GitBase` is in internally used by other classes and may change, potentially breaking this plugin. I think extending from `Plugin` gives you the necessary basics (including the elements for the repo url), but let's find out...
- If I follow the code correctly, we could get the `repo` object later than in the `init()` phase, perhaps grab it when it is used with `this.config.getContext('repo')` (I have just added some tests to verify this is available in https://github.com/release-it/release-it/commit/c628990110d36cb62db948bc47a6762adacb957d)

Let me know whether this helps or not!

**Comment by darekkay** [comment]
Thanks @webpro , using `this.config.getContext()` instead of `this.getContext()` did the trick 🙂
